openapi: 3.0.3
info:
  title: System API - Crea Saludo
  description: Microservicio que genera un saludo personalizado
  version: 1.0.0
servers:
  - url: http://localhost:8081/api/v1
tags:
  - name: Saludo
    description: Operaciones relacionadas con el saludo
paths:
  /api/v1/saludo/{name}:
    get:
      tags:
        - Saludo
      summary: Obtiene un saludo personalizado
      operationId: getSaludo
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: Nombre de la persona a saludar
      responses:
        "200":
          description: Saludo generado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SaludoResponse"
        "400":
          description: Petición inválida
        "500":
          description: Error interno del servidor
components:
  schemas:
    SaludoResponse:
      type: object
      properties:
        saludo:
          type: string
          example: "Hola, Juan"
